name: build
on: [push, pull_request]

jobs:
  build_exe:
    runs-on: windows-2025
    steps:
    - uses: actions/checkout@v4 

    # 全局缓存配置
    - name: Cache Python dependencies
      uses: actions/cache@v4
      id: cache-pip
      with:
        path: |
          ~\AppData\Local\pip\Cache
          ~\AppData\Local\nuitka\Cache
          ~\.cache\pip
          ~\.cache\nuitka
        key: ${{ runner.os }}-python-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Setup Python
      uses: actions/setup-python@v5.6.0
      with:
        # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
        python-version: 3.13.3
        # File containing the Python version to use. Example: .python-version
        #python-version-file: # optional
        # Used to specify a package manager for caching in the default directory. Supported values: pip, pipenv, poetry.
        cache: pip
        cache-dependency-path: requirements.txt  # 根据依赖文件生成缓存key
        # The target architecture (x86, x64, arm64) of the Python or PyPy interpreter.
        #architecture: # optional
        # Set this option if you want the action to check for the latest available version that satisfies the version spec.
        #check-latest: # optional
        # The token used to authenticate when fetching Python distributions from https://github.com/actions/python-versions. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
        #token: # optional, default is ${{ github.server_url == 'https://github.com' && github.token || '' }}
        # Used to specify the path to dependency files. Supports wildcards or a list of file names for caching multiple dependencies.
        #cache-dependency-path: # optional
        # Set this option if you want the action to update environment variables.
        #update-environment: # optional, default is true
        # When 'true', a version range passed to 'python-version' input will match prerelease versions if no GA versions are found. Only 'x.y' version range is supported for CPython.
        #allow-prereleases: # optional
        # When 'true', use the freethreaded version of Python.
        #freethreaded: # optional

    - name: Install Dependencies
      run: pip install -r requirements.txt
      # 仅在缓存未命中时显示完整输出
      if: steps.cache-pip.outputs.cache-hit != 'true'

    - name: Build exe with Nuitka
      run: |
        pip install -U nuitka
        mkdir -p build
        nuitka --jobs=4 --assume-yes-for-downloads --lto=yes --output-dir=build --onefile --standalone --enable-plugin=tk-inter CSDemoDownloader.py
      env:
        # 启用Nuitka编译缓存
        NUITKA_CACHE_DIR: ~\AppData\Local\nuitka\Cache
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: nuitka-build
        path: build
        retention-days: 1  # 临时存储

  
  publish_release:
    needs: [build_exe]  # 依赖构建任务
    runs-on: ubuntu-latest
    if: github.event_name == 'push'  # 仅在push事件触发
    permissions:
      contents: write  # 需要写入权限发布Release
    steps:
    - uses: actions/checkout@v4
    
    # 下载构建产物
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: nuitka-build
        path: build

    # 获取短SHA
    - name: Extract Short SHA
      run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: Build-${{ env.SHORT_SHA }}
        name: "Build ${{ env.SHORT_SHA }}"
        body: |
          ${{ github.event.head_commit.message }}
          Commit: ${{ env.SHORT_SHA }}
          ###### 由 GitHub Actions 自动生成
        files: |
          build/*.exe
        draft: false
        prerelease: true
